{
 "title": "Vault KMS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(rate(kms_request_sum{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[1m]))*60",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "CPU Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\", image!=\"\"}[5m])) by (container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\", image!=\"\"}) by (container)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory Usage (WSS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\", image!=\"\"}) by (container)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", image!=\"\"}) by (container) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container!=\"\", image!=\"\"}) by (container) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container != \"\", container != \"POD\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", container != \"\", container != \"POD\"}) by (container)"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rate of Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Pod - Read & Writes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m])))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "ThroughPut",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution(Containers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(container) (rate(container_fs_reads_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\", pod=\"$pod\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Storage IO - Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Current Storage IO",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    },
    {
     "expr": "sum by(container) (rate(container_fs_writes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    },
    {
     "expr": "sum by(container) (rate(container_fs_reads_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]) + rate(container_fs_writes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    },
    {
     "expr": "sum by(container) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    },
    {
     "expr": "sum by(container) (rate(container_fs_writes_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    },
    {
     "expr": "sum by(container) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\",namespace=\"kube-system\", pod=\"vault-kms-provider-kms-vault-control-plane\"}[5m]))"
    }
   ]
  }
 ]
}