version: 3
vars:
  KIND_CLUSTER_NAME: kms-vault
  KIND_CLUSTER_VERSION: 1.24
  ENABLED_PROVIDERS:
    sh: '([ -z "$ENABLED_PROVIDERS" ] && echo --enabled-providers=debug) || echo $ENABLED_PROVIDERS'
silent: true
includes:
  cluster: .task/cluster.yml
  docker: .task/docker.yml
  fetch: .task/fetch.yml
  go: .task/go.yml
  prod: .task/prod.yml
tasks:
  default:
    cmds:
      - task -l
  bin-dir:init:
    desc: create bin directory
    cmds:
      - mkdir -p ./bin
    status:
      - test -d ./bin
  run-dir:init:
    desc: create bin directory
    cmds:
      - mkdir -pm 777 bin/run
      - mkdir -pm 777 bin/run/debug
      - mkdir -pm 777 bin/run/vault
      - mkdir -pm 777 bin/run/awskms
    status:
      - test -d ./bin/run
      - test -d ./bin/run/debug
      - test -d ./bin/run/vault
      - test -d ./bin/run/awskms
  example:load:
    desc: load demo data
    cmds:
      - sh {{.SCRIPT}}/test.bash
  example:before-key-rotate:
    desc: data before key rotate
    cmds:
      - echo "-------- secret etcd data --------"
      -  ./bin/kubectl -n kube-system exec -t etcd-kms-vault-control-plane -- etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt  --cert=/etc/kubernetes/pki/etcd/server.crt  --key=/etc/kubernetes/pki/etcd/server.key  get /registry/secrets/default/data-test
      -  echo "-------- secret fetch data --------"
      - ./bin/kubectl get secret data-test -o yaml
  example:after-key-rotate:
    desc: data after key rotate
    cmds:
      -  ./bin/kubectl apply -f scripts/secret2.yaml
      - echo "-------- old secret etcd --------"
      -  ./bin/kubectl -n kube-system exec -t etcd-kms-vault-control-plane -- etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt  --cert=/etc/kubernetes/pki/etcd/server.crt  --key=/etc/kubernetes/pki/etcd/server.key  get /registry/secrets/default/data-test
      - echo "-------- new secret etcd --------"
      -  ./bin/kubectl -n kube-system exec -t etcd-kms-vault-control-plane -- etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt  --cert=/etc/kubernetes/pki/etcd/server.crt  --key=/etc/kubernetes/pki/etcd/server.key  get /registry/secrets/default/data-test3
      -  echo "-------- old secret fetch data --------"
      - ./bin/kubectl get secret data-test -o yaml
      -  echo "-------- new secret fetch data --------"
      - ./bin/kubectl get secret data-test3 -o yaml
