---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /etc/kubernetes/encryption-config.yaml
    hostPath: scripts/encryption-config.yaml
    readOnly: true
    propagation: None
  - containerPath: /etc/kubernetes/vault-kms-provider.yaml
    hostPath: tests/e2e/generated_manifests/config.yaml
    readOnly: true
    propagation: None
  - containerPath: /etc/kubernetes/manifests/kubernetes-kms.yaml
    hostPath: tests/e2e/generated_manifests/kms.yaml
    readOnly: true
    propagation: None
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          encryption-provider-config: "/etc/kubernetes/encryption-config.yaml"
        extraVolumes:
        - name: encryption-config
          hostPath: "/etc/kubernetes/encryption-config.yaml"
          mountPath: "/etc/kubernetes/encryption-config.yaml"
          readOnly: true
          pathType: File
        - name: sock-path
          hostPath: "/opt"
          mountPath: "/opt"