
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: data-test
  namespace: default
stringData:
  config.yaml: |
     provider: test
---

kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: data-test2
  namespace: default
stringData:
  config.yaml: |
     provider: test2