apiVersion: v1
kind: ServiceAccount
metadata:
  name: trousseau-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: role-tokenreview-binding
   labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: trousseau-auth
  namespace: kube-system