services:
  init:
    image: busybox:stable-glibc
    command: sh -c 'mkdir -p /sockets/awskms /sockets/vault /sockets/trousseau ; chown -R 10123:10123 /sockets/*'
    volumes:
      - sockets:/sockets:rw
  proxy:
    image: ${TR_PROXY_IMAGE}
    command: --listen-addr=unix:///opt/trousseau-kms/proxy.socket --trousseau-addr=/sockets/trousseau/trousseau.socket
    volumes:
      - sockets:/sockets:rw
      - ${TR_SOCKET_LOCATION}:/opt/trousseau-kms:rw
    restart: always
    depends_on:
      - trousseau
  trousseau:
    image: ${TR_TROUSSEAU_IMAGE}
    command: --listen-addr=unix:///sockets/trousseau/trousseau.socket --socket-location=/sockets ${TR_ENABLED_PROVIDERS} -v=${TR_VERBOSE_LEVEL}
    volumes:
      - sockets:/sockets:rw
    restart: always
    depends_on:
      - init
      - awskms
      - vault
volumes:
  sockets: {}
