---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /etc/kubernetes/encryption-config.yaml
    hostPath: scripts/hcvault/archives/localdev/encryption-config.yaml
    readOnly: true
    propagation: None
  - containerPath: /opt/vault-kms/vaultkms.socket
    hostPath: vaultkms.socket
    readOnly: true
    propagation: None
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          encryption-provider-config: "/etc/kubernetes/encryption-config.yaml"
        extraVolumes:
        - name: encryption-config
          hostPath: "/etc/kubernetes/encryption-config.yaml"
          mountPath: "/etc/kubernetes/encryption-config.yaml"
          readOnly: true
          pathType: File
        - name: sock-path
          hostPath: "/opt"
          mountPath: "/opt"