FROM golang@sha256:89a56cb4a3551108b5c447d2893a774db8517e8cc9a72f82abe84078eca7675a AS base
WORKDIR /work
ADD ./go.* ./
RUN go mod download

FROM base AS worker
WORKDIR /work
ADD . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kubernetes-kms-vault trousseau/main.go

FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:b37d34ffce0e59879c776da3f1b1c643674975e6588fe8e8adf60eef25b4a6ca
LABEL org.opencontainers.image.source https://github.com/ondat/trousseau
COPY --from=worker /work/kubernetes-kms-vault /bin/
ENTRYPOINT ["/bin/kubernetes-kms-vault"]
