FROM golang@sha256:89a56cb4a3551108b5c447d2893a774db8517e8cc9a72f82abe84078eca7675a AS base
WORKDIR /work
ADD ./go.* ./
RUN go mod download

FROM base AS worker
WORKDIR /work
ADD . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kubernetes-kms-vault trousseau/main.go

FROM ubuntu@sha256:31cd7bbfd36421dfd338bceb36d803b3663c1bfa87dfe6af7ba764b5bf34de05 
LABEL org.opencontainers.image.source https://github.com/Trousseau-io/trousseau
COPY --from=worker /work/kubernetes-kms-vault /bin/
ENTRYPOINT ["/bin/kubernetes-kms-vault"]
