# server: https://<address>:9345    #to edit/uncomment for second and third control plane node
# token: <rke2_server_token>             #to edit/uncomment for second and third control plane node
kube-apiserver-arg:
  - "--encryption-provider-config=/var/lib/rancher/rke2/server/cred/vault-kms-encryption-config.yaml" 
kube-apiserver-extra-mount:
  - "/opt/trousseau-kms:/opt/trousseau-kms"
