namespace: kube-system
commonLabels:
  tier: control-plane
  app: trousseau-kms-provider
resources:
- rbac.yaml
- daemonset.yaml
- configmap-awskms.yaml
# Enable if you have the Vault config generator
# - configmap-vault.yaml
patchesStrategicMerge:
- sidecar-awskms.yaml
- sidecar-vault.yaml
# Enable if you have the Vault config generator
# - configmap-vault-generator.yaml