#!/usr/bin/env bash

set -e

if [[ -n "$(git status --short)" ]]; then
    git stash
    function unstash() {
        git reset --hard
        git stash pop
    }
    trap unstash EXIT
fi

task go:fmt go:vet go:gosec go:golangci go:unit-tests

git diff --exit-code --quiet || (git status && exit 1)
