name: e2e test on pr

on:
  workflow_call:
    inputs:
      provider:
        required: true
        default: "debug"
        type: string
      kubever:
        required: true
        default: "1.24"
        type: string

env:
  DOCKER_REGISTRY: local
  IMAGE_NAME: trousseau
  IMAGE_VERSION: e2e

jobs:
  e2e:
    name: kuttl e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: e2e test
        run: make go:e2e-tests:${{ inputs.provider }} KIND_CLUSTER_VERSION=${{ inputs.kubever }}
      - uses: actions/upload-artifact@v3
        if: ${{ always() }} 
        with:
          name: kind-logs
          path: kind-logs-*
