name: golangci-lint

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

permissions: 
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-go@4a4352b33067e47da692b40ea6e19467075219ac
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: golangci-lint
        uses: golangci/golangci-lint-action@c3ef0c370269e2a25b67c7f8e03d37e6cb106cb9
        with:
          version: latest
          working-directory: ${{ inputs.project }}
