name: "gosec"

on: workflow_call 

permissions: 
  contents: read
  pull-requests: read

jobs:
  build:
    name: scan
    runs-on: ubuntu-latest
    env: 
      GO111MODULE: on
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: run gosec scan
        uses: securego/gosec@a64cde55a4499d951566243783f204e94b9197ed
        with: 
          args: "./..." 
