name: Trousseau e2e on pr

on:
  pull_request:
    branches: [ main, v2* ]
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read
  actions: read
  security-events: write
  packages: write

concurrency:
  group: ci-e2e-trousseau-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  golangci-lint:
    uses: ./.github/workflows/_gocilint.yml
    with:
      project: trousseau
  
  gosec-scanning:
    uses: ./.github/workflows/_gosecscan.yml
    needs: golangci-lint
    
  image-build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      registry: ghcr.io
      imageName: ${{ github.repository }}
      imageTagPrefix: trousseau
      project: trousseau
    needs: gosec-scanning

  e2e:
    uses: ./.github/workflows/_e2e-test.yml
    with:
      provider: debug
    needs: image-build

  image-vulnerability-scan:
    uses: ./.github/workflows/_trivy.yml
    with:
      registry: ghcr.io
      imageName: ${{ github.repository }}
      imageTagPrefix: trousseau
    needs: image-build