name: Generator test on pr

on:
  pull_request:
    branches: [ main, v2* ]
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read
  actions: read
  security-events: write
  packages: write

concurrency:
  group: ci-generator-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  docker-compose:
    name: docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "trousseau-env"
          FILE_DATA: |
            TR_VERBOSE_LEVEL=3
            TR_ENABLED_PROVIDERS="--enabled-providers=awskms --enabled-providers=vault"
            TR_SOCKET_LOCATION=${PWD}/bin/run
            TR_PROXY_IMAGE=ondat/trousseau:proxy-develop
            TR_AWSKMS_IMAGE=ondat/trousseau:awskms-develop
            TR_VAULT_IMAGE=ondat/trousseau:vault-develop
            TR_TROUSSEAU_IMAGE=ondat/trousseau:trousseau-develop
            TR_AWSKMS_CREDENTIALS=${HOME}/.aws/credentials
            TR_AWSKMS_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/awskms.yaml
            TR_VAULT_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/vault.yaml
      - name: generate services
        run: make prod:generate:docker-compose ENV_LOCATION=trousseau-env
  kustomize:
    name: kustomize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "awskms.yaml"
          FILE_DATA: |
            profile: default
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "trousseau-env"
          FILE_DATA: |
            TR_VERBOSE_LEVEL=3
            TR_ENABLED_PROVIDERS="--enabled-providers=awskms --enabled-providers=vault"
            TR_SOCKET_LOCATION=${PWD}/bin/run
            TR_PROXY_IMAGE=ondat/trousseau:proxy-develop
            TR_AWSKMS_IMAGE=ondat/trousseau:awskms-develop
            TR_VAULT_IMAGE=ondat/trousseau:vault-develop
            TR_TROUSSEAU_IMAGE=ondat/trousseau:trousseau-develop
            TR_AWSKMS_CREDENTIALS=${HOME}/.aws/credentials
            TR_AWSKMS_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/awskms.yaml
            TR_VAULT_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/vault.yaml
            TR_VAULT_ADDRESS=http://127.0.0.1:8200
      - name: generate services
        run: make prod:generate:kustomize ENV_LOCATION=trousseau-env
  helm:
    name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "awskms.yaml"
          FILE_DATA: |
            profile: default
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "trousseau-env"
          FILE_DATA: |
            TR_VERBOSE_LEVEL=3
            TR_ENABLED_PROVIDERS="--enabled-providers=awskms --enabled-providers=vault"
            TR_SOCKET_LOCATION=${PWD}/bin/run
            TR_PROXY_IMAGE=ondat/trousseau:proxy-develop
            TR_AWSKMS_IMAGE=ondat/trousseau:awskms-develop
            TR_VAULT_IMAGE=ondat/trousseau:vault-develop
            TR_TROUSSEAU_IMAGE=ondat/trousseau:trousseau-develop
            TR_AWSKMS_CREDENTIALS=${HOME}/.aws/credentials
            TR_AWSKMS_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/awskms.yaml
            TR_VAULT_CONFIG=${PWD}/tests/e2e/kuttl/kube-v1.24/vault.yaml
            TR_VAULT_ADDRESS=http://127.0.0.1:8200
      - name: generate services
        run: make prod:generate:helm ENV_LOCATION=trousseau-env
